version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set region $REGION

  pre_build:
    commands:
      - terraform version
      - aws sts get-caller-identity

  build:
    commands:
      - terraform init -backend-config="key=prod/terraform.tfstate"
      - terraform apply -var-file=prod.terraform.tfvars --auto-approve -lock=false

  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - '**/*'
  base-directory: '.'
