version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set region $REGION

  pre_build:
    commands:
      - terraform version
      - aws sts get-caller-identity
      - mkdir -p tfplan-output
      - aws s3 cp s3://jeff-tf-outfile/terraform/dev/plans/tfplan ./tfplan
  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}
      - terraform init -backend-config="key=dev/terraform.tfstate"
      - terraform apply tfplan

  post_build:
    commands:
      - echo apply stage completed 

# No artifacts needed in apply stage since we're only consuming the plan
