version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set region $REGION

  pre_build:
    commands:
      - terraform version
      - aws sts get-caller-identity

  build:
    commands:
      - "cd ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}"
      - terraform init -backend-config="key=dev/terraform.tfstate"
      - terraform plan -var-file=dev.terraform.tfvars --out=dev-output/tfplan

  post_build:
    commands:
      - echo dev plan stage completed
      - cp dev-output/tfplan ${CODEBUILD_SRC_DIR}/dev-output/

artifacts:
  files:
    - tfplan
  base-directory: dev-output
  name: dev-tfplan
  discard-paths: yes
  secondary-artifacts:
    TerraformPlan:
      files:
        - tfplan
      base-directory: dev-output
      name: terraform-dev-plan
      bucket-name: jeff-tf-outfile
      path: terraform/dev/plans/
